.INCLUDE "usb1286def.inc"
.ORG $00

;Initialize stack pointer
LDI R16, LOW(RAMEND)		; SET THE STACK POINTER
OUT SPL, R16
LDI R16, HIGH(RAMEND)
OUT SPH, R16

LDI R16, $FF				; SET THE DATA DIRECTION
OUT DDRC, R16
COM R16
OUT DDRE, R16

LDI R19, $FF				; LOAD THE OFF STATE OF THE LED
LDI R18, 0b11111110			; LOAD THE ON STATE OF THE LED
LDI R16, $00				; LOAD THE LOW ADDRESS OF EEPROM
LDI R17, $05				; LOAD THE HIGH ADDRESS OF EEPROM

CALL EEPROM_READ_DATA		; LOAD INITIAL STATE OF THE EEPROM ADDRESS
OUT PORTC, R20			; DISPLAY IT ON BARGRAPH

BEGIN:
CALL EEPROM_READ_DATA		; LOAD INITIAL STATE
OUT PORTC, R20			; LOADS ORIGINAL STATE
CALL CHECK_S2				; CHECK IF SWITCH IS PUSHED
CALL PAUSE				; BEGIN THE DELAY ROUTINE
CALL EEPROM_WRITE_DATA		; WRITE R18 TO EEPROM 
CPI R18, $FE				; COMPARE R18 WITH ON STATE
BREQ CLEAR_LED			; IF ON, CLEAR LED
CPI R18, $FF				; COMPARE R18 WITH OFF STATE
BREQ SET_LED				; IF OFF, TURN ON LED

SET_LED:
	LDI R18, $FE			; LOAD ON STATE
	RJMP BEGIN			; RETURN

CLEAR_LED:
	LDI R18, $FF			; LOAD OFF STATE
	RJMP BEGIN			; RETURN

HERE: RJMP HERE

CHECK_S2:
L1:
	SBIC PINE, 0			; WAIT FOR ACTIVE LOW SWITCH TO BE PUSHED
	RJMP L1			; WAIT
	RJMP END			; RETURN WHEN PUSHED
END:
	RET

PAUSE:
		LDI R24, 10				; FIRST LOOP
	LOOP1:	
		LDI R22, 100				; SECOND LOOP
	LOOP2:
		LDI R23, 60				; THIRD LOOP
	LOOP3:
		NOP 					; WASTE TIME
		OUT PORTC, R20			; OUTPUT R20
		CALL CHECK_S2				; CHECK SWITCH
		DEC R23 				; DECREMENT THIRD LOOP
		
		BRNE LOOP3				; WAIT FOR END OF LOOP
		CALL CHECK_S2				; CHECK SWITCH
		DEC R22				; DECREMENT SECOND LOOP
		
		BRNE LOOP2				; WAIT FOR END OF LOOP
		CALL CHECK_S2				; CHECK SWITCH
		DEC R24				; DECREMENT FIRST LOOP
		BRNE LOOP1				; WAIT FOR END OF LOOP
		RET					; RETURN
	
EEPROM_WRITE_DATA:
	; EEPROM WRITE DATA SUBROUTINE
	WAIT:
	SBIC 	EECR, EEPE
	RJMP	WAIT
	OUT 	EEARH, R17
	OUT 	EEARL, R16
	OUT 	EEDR, R18
	SBI 	EECR, EEMPE
	SBI 	EECR, EEPE
	RET

EEPROM_READ_DATA:
	; EEPROM READ DATA SUBROUTINE
	WAIT2:
	SBIC 	EECR, EEPE
	RJMP 	WAIT2
	OUT 	EEARH, R17
	OUT 	EEARL, R16
	SBI 	EECR, EEPE
	IN 	R20, EEDR
	RET