.INCLUDE "usb1286def.inc"
.ORG 0x00

LDI R16, HIGH(RAMEND)
OUT SPH, R16
LDI R16, LOW(RAMEND)
OUT SPL, R16

LDI R16, $00 
OUT DDRE, R16					;SET PORT E AS AN INPUT
LDI R16, $FF
OUT DDRC, R16					;SET PORT C AS AN OUTPUT 

LDI R16, 0x00					;SET POINTER LOW
LDI R17, 0x01					;SET POINTER HIGH

CALL EEPROM_READ_DATA			;READ IN DATA
COM R20					;COMPLIMENT
RJMP HERE

BUTTON_PUSH:
	IN R20, PINE				;BRING IN DATA FROM PORT E
	COM R20				;CHANGE ACTIVE LOW TO ACTIVE HIGH
	LSR R20				;SHIFT RIGHT
	LSR R20				;SHIFT RIGHT
	LSR R20				;SHIFT RIGHT
	LSR R20				;SHIFT RIGHT
	LSR R20				;SHIFT RIGHT

	CALL LOOP_UP_SQUARED
	ADD R20, R20				;MULTIPLY R20 BY 2
	ADD R20, R21				;ADD x^2 TO 2x
	SUBI R20, -9				;ADD 9 TO EXISTING VALUE
	CALL EEPROM_WRITE_DATA
	COM R20				;COMPLIMENT FOR OUTPUT

HERE:
	OUT PORTC, R20			;SEND DATA TO PORT C
	SBIC PINE, 0				;WAIT FOR BUTTON PUSH
	RJMP HERE
	RJMP BUTTON_PUSH

EEPROM_WRITE_DATA:
	SBIC EECR, EEPE			;CHECK ENABLE
	RJMP EEPROM_WRITE_DATA		;IF ENABLE IS SET THEN BRANCH
	OUT EEARL, R16			;SET THE POINTER
	OUT EEARH, R17			;SET THE POINTER
	OUT EEDR, R20				;WRITE THE DATA
	SBI EECR, EEMPE			;SET THE MASTER ENABLE
	SBI EECR, EEPE			;SET THE ENABLE
	RET

EEPROM_READ_DATA:
	SBIC EECR, EEPE			;CHECK ENABLE
	RJMP EEPROM_READ_DATA		;IF THE ENABLE IS SET THEN BRANCH
	OUT EEARL, R16			;SET THE POINTER
	OUT EEARH, R17			;SET THE POINTER
	SBI EECR, EERE			;SET READ ENABLE
	IN R20, EEDR				;GET THE DATA
	RET

LOOP_UP_SQUARED:
	LDI ZH, HIGH(DATA<<1)
	LDI ZL, LOW(DATA<<1)
	ADD ZL, R20
	LPM R21, Z
	RET

DATA: .DB 0, 1, 4, 9, 16, 25, 36, 49 
